### ISSUE TITLE
v1.0.0 无法登陆

### ISSUE THREAD

**Issue by idreamshen** [idreamshen/hass-volvooncall-cn#6]
已知问题，仍然解决中。

产生的原因是服务端接口开启了 sign 参数校验。目前正在还原 sign 的计算逻辑。

**Comment by shulkx** [comment]
`sign`是指`v587sign`吗？

**Comment by idreamshen** [comment]
> `sign`是指`v587sign`吗？

是的

**Comment by shulkx** [comment]
我这有从小程序抓的算法，是javascript的，需要的话发给你

**Comment by idreamshen** [comment]
> 我这有从小程序抓的算法，是javascript的，需要的话发给你

方便的话发一份给我 gmail 邮箱，感谢

**Comment by shulkx** [comment]
> > 我这有从小程序抓的算法，是javascript的，需要的话发给你
> 
> 方便的话发一份给我 gmail 邮箱，感谢

已发，几个月前抓的，不确定时效性。不过提供一个思路，小程序的请求也带这个参数，比app好还原一些，我看过app的代码，根本找不到头，但同样不确定小程序是不是适用app的登录……

**Comment by hphuangpu** [comment]
我能把HA装上已经不容易了，我也没能力研究这个东西，能用上VOC就拜托各位大佬了。。

**Comment by yanandy123** [comment]
大佬们加油，我的目标是实现停车后，gps回家开暖气or冷气

**Comment by Nana2222** [comment]
支持大佬开发

**Comment by idreamshen** [comment]
登陆问题已修复。可使用 v1.0.1 该版本。

**Comment by hphuangpu** [comment]
> 登陆问题已修复。可使用 v1.0.1 该版本。

真是个大好人，我试试去~
